language: node_js

node_js:
  - "stable"

before_install:
  # Install GitBook
  - npm install gitbook-cli -g
  - npm install svgexport -g
  - gitbook fetch 3.2.3

install:
  # Install GitBook dependencies
  - echo "install gitbook dependencies..."
  - gitbook install

script:
  - echo "build blog..."
  - gitbook build

before_deploy:
  # Set up git user name and tag this commit
  #- git config --local user.name "YOUR GIT USER NAME"
  #- git config --local user.email "YOUR GIT USER EMAIL"
  - git tag "$(date +'%Y%m%d_%H%M%S')-$(git log --format=%h -1)"
  #- wget https://github.com/billryan/blog/files/1762412/original.tar.gz
  #- tar xzvf original.tar.gz
  #- rsync -aP original/ _book/
  - tar czvf blog.tar.gz _book/

deploy:
  - provider: pages
    skip-cleanup: true
    github-token:
      secure:
        cBMDcuMqkIi6eJEDmX0kHZRC31JT9n6srKujh3ux9iQGNZTtd+bn+tPk5geTiCdBRci0ss4Ub6UyqdBtp7byiun5w4t8vACp7l3J+BMnGpFa804OTTZ34iqxqWvkXwRGsYPXDf4ayHZA48rsKfdMavv6gOchfFv0huXJUzJI++/o9e/5JKMaeuNS9H+t4Pw9LiUSMjUFrngCMDxEfYUkk9UxBGPPcEEolJkIkXrmpkjt3qzhxl1qczOJ8DwFrJvBuooFIKRRBgEZQU1rysDxPBPAeDwqfYKWR2UBzNttOGrpedPq8gA5jXhcLvlxpxjsfbvxSi4boNiKt24L3SGYZGdyYMNMz7kJ3R7yZiWrhfknx0KL85l+C9DU0Gc7nFG+3O8xrQ8YOF6ExFS0hEu2tvaEJUej5XMSV4cOnF4GnAQGmnqvHMtXsb01s6Bcw7qBl4jXB5b1k/72QT+TjM57LPkdLHVI29KMifFBOc30DZDEuYrHydNN/+BeSb2ery7jWypkxDVMW0v5ZWrrTvybtRbhGHAQL0bLIyckQWfTl29S0nQPQgoMshI6MNEL4VQ2L0IOaJppBixrYnjIgQH+JPnlOalDxcCwz3K+cEK9eO4wrIQ/PV6quOgmjDGa07iqliMTs77R3GNljyajQeEkeQqZjmvySfCnXOtNRC3WESE=
    keep-history: true
    local-dir: _book
    on:
      branch: blog
    target-branch: master
  - provider: releases
    api_key:
      secure:
        cBMDcuMqkIi6eJEDmX0kHZRC31JT9n6srKujh3ux9iQGNZTtd+bn+tPk5geTiCdBRci0ss4Ub6UyqdBtp7byiun5w4t8vACp7l3J+BMnGpFa804OTTZ34iqxqWvkXwRGsYPXDf4ayHZA48rsKfdMavv6gOchfFv0huXJUzJI++/o9e/5JKMaeuNS9H+t4Pw9LiUSMjUFrngCMDxEfYUkk9UxBGPPcEEolJkIkXrmpkjt3qzhxl1qczOJ8DwFrJvBuooFIKRRBgEZQU1rysDxPBPAeDwqfYKWR2UBzNttOGrpedPq8gA5jXhcLvlxpxjsfbvxSi4boNiKt24L3SGYZGdyYMNMz7kJ3R7yZiWrhfknx0KL85l+C9DU0Gc7nFG+3O8xrQ8YOF6ExFS0hEu2tvaEJUej5XMSV4cOnF4GnAQGmnqvHMtXsb01s6Bcw7qBl4jXB5b1k/72QT+TjM57LPkdLHVI29KMifFBOc30DZDEuYrHydNN/+BeSb2ery7jWypkxDVMW0v5ZWrrTvybtRbhGHAQL0bLIyckQWfTl29S0nQPQgoMshI6MNEL4VQ2L0IOaJppBixrYnjIgQH+JPnlOalDxcCwz3K+cEK9eO4wrIQ/PV6quOgmjDGa07iqliMTs77R3GNljyajQeEkeQqZjmvySfCnXOtNRC3WESE=
    file: blog.tar.gz
    skip_cleanup: true
    on:
      branch: blog

# whitelist
branches:
  only:
    - blog
